# Generated by Django 4.1 on 2022-11-23 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user_pk",
        ),
    ]
