# Generated by Django 4.1 on 2022-11-23 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_remove_profile_user_pk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
    ]
