# Generated by Django 4.1 on 2022-11-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_remove_profile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user_pk",
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
