# Generated by Django 4.1 on 2022-11-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_profile_user_pk"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="nickname",
            new_name="display_name",
        ),
    ]
