# Generated by Django 4.1 on 2022-11-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_rename_nickname_profile_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_individual",
            field=models.BooleanField(default=True),
        ),
    ]
