# Generated by Django 4.1 on 2022-12-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_profile_open_to_company_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="user_pk",
            field=models.IntegerField(default=0),
        ),
    ]
