# Generated by Django 4.1 on 2022-12-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_remove_experience_preference_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="field",
            name="preference",
            field=models.IntegerField(blank=True),
        ),
    ]
