# Generated by Django 4.1 on 2022-12-06 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0014_alter_field_name_alter_field_preference_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="recommend_users",
        ),
        migrations.CreateModel(
            name="RecommendProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_pk", models.IntegerField()),
                ("match_ratio", models.FloatField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.company",
                    ),
                ),
            ],
        ),
    ]
