# Generated by Django 4.1 on 2022-12-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_remove_company_recommend_users_recommendprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendprofile",
            name="skills",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
