# Generated by Django 4.1 on 2022-08-25 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='javascript',
            name='child_skills',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roadmap.javascript'),
        ),
    ]
