# Generated by Django 4.1 on 2022-08-25 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_alter_javascript_child_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='javascript',
            name='child_skills',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='roadmap.javascript'),
        ),
    ]
