# Generated by Django 4.1 on 2022-08-25 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0003_alter_javascript_child_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='js_url',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_skill', to='roadmap.javascript'),
        ),
    ]
