# Generated by Django 4.1 on 2022-08-25 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0006_rename_child_skills_javascript_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='js_url',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url', to='roadmap.javascript'),
        ),
    ]
