# Generated by Django 4.1 on 2022-08-29 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0008_skills_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='js_url',
            name='skill',
        ),
        migrations.DeleteModel(
            name='JavaScript',
        ),
        migrations.DeleteModel(
            name='js_url',
        ),
    ]
