# Generated by Django 4.1 on 2022-12-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0009_remove_js_url_skill_delete_javascript_delete_js_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="skills",
            name="level",
            field=models.IntegerField(default=-1),
        ),
    ]
