# Generated by Django 4.1 on 2022-08-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
                ('experience_level', models.CharField(max_length=100)),
                ('expiration', models.CharField(max_length=100)),
                ('keywords', models.ManyToManyField(to='crawling.keyword')),
            ],
        ),
    ]
