# Generated by Django 4.1 on 2022-08-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='experience_level',
        ),
        migrations.AddField(
            model_name='data',
            name='career_min',
            field=models.IntegerField(default=0),
        ),
    ]
