# Generated by Django 4.1 on 2022-08-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0003_remove_data_expiration_data_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
