# Generated by Django 4.1 on 2022-11-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawling", "0004_keyword_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="trend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("keywords", models.ManyToManyField(to="crawling.keyword")),
            ],
        ),
    ]
