# Generated by Django 4.1 on 2022-08-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='like_count',
        ),
        migrations.AddField(
            model_name='test',
            name='user_id',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
