# Generated by Django 4.1 on 2022-08-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devApp', '0003_dummy'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('title', models.TextField()),
                ('likes', models.IntegerField()),
                ('level', models.IntegerField()),
                ('curriculum', models.TextField()),
            ],
        ),
    ]
