# Generated by Django 4.1 on 2022-08-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devApp', '0004_temp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dummy',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
