# Generated by Django 4.1 on 2022-08-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devApp', '0006_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('addr', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
    ]
